In [1]:
import numpy as np
import torch

In [23]:
x = torch.empty(5,3)

x = x.new_ones(5, 3)
y = torch.rand(x.shape)

print(x+y)
print(torch.add(x, y))

tensor([[1.4068, 1.5860, 1.3254],
        [1.0115, 1.9958, 1.7099],
        [1.5171, 1.7475, 1.9110],
        [1.1012, 1.8278, 1.5081],
        [1.1725, 1.5103, 1.7078]])
tensor([[1.4068, 1.5860, 1.3254],
        [1.0115, 1.9958, 1.7099],
        [1.5171, 1.7475, 1.9110],
        [1.1012, 1.8278, 1.5081],
        [1.1725, 1.5103, 1.7078]])


In [24]:
result = torch.empty(x.shape)
torch.add(x, y, out = result)
result

tensor([[1.4068, 1.5860, 1.3254],
        [1.0115, 1.9958, 1.7099],
        [1.5171, 1.7475, 1.9110],
        [1.1012, 1.8278, 1.5081],
        [1.1725, 1.5103, 1.7078]])

In [37]:
## Any operation that mutates a tensor in place is post fixed by a _
y.add_(x)

tensor([[7.4068, 7.5860, 7.3254],
        [7.0115, 7.9958, 7.7099],
        [7.5171, 7.7475, 7.9110],
        [7.1012, 7.8278, 7.5081],
        [7.1725, 7.5103, 7.7078]])

In [59]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [75]:
x = torch.randn(4,4)
x = x.numpy() ## converts torch tensor to numpy array
print(type(x))

x = torch.from_numpy(x) ## converts numby array to torch tensor
print(type(x))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [80]:
if (torch.cuda.is_available()):
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to("cuda", torch.float32)
    z = x+y
    z.to("cpu", torch.double)

In [86]:
%timeit torch.lu(torch.randn(5000, 5000, device="cuda"))

171 ms ± 747 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [87]:
%timeit torch.lu(torch.randn(5000, 5000, device="cpu"))

820 ms ± 26.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
