In [3]:
import torch
from torch import nn
import numpy as np

In [15]:
lstm = nn.LSTM(3, 3)  # Input dim is 3, output dim is 3
inputs = [torch.randn(1, 3) for _ in range(3)]  # make a sequence of length 5
print(inputs, "\n")
# initialize the hidden state.
hidden = (torch.randn(1, 1, 3),
          torch.randn(1, 1, 3))
for i in inputs:
    # Step through the sequence one element at a time.
    # after each step, hidden contains the hidden state.
    out, hidden = lstm(i.view(1, 1, -1), hidden)
    print(i.view(1, 1, -1))

[tensor([[-0.4695, -1.3311,  1.6182]]), tensor([[-0.2466, -0.6993, -0.7350]]), tensor([[ 0.9755, -0.9425, -1.0564]])] 

tensor([[[-0.4695, -1.3311,  1.6182]]])
tensor([[[-0.2466, -0.6993, -0.7350]]])
tensor([[[ 0.9755, -0.9425, -1.0564]]])


In [16]:

# alternatively, we can do the entire sequence all at once.
# the first value returned by LSTM is all of the hidden states throughout
# the sequence. the second is just the most recent hidden state
# (compare the last slice of "out" with "hidden" below, they are the same)
# The reason for this is that:
# "out" will give you access to all hidden states in the sequence
# "hidden" will allow you to continue the sequence and backpropagate,
# by passing it as an argument  to the lstm at a later time
# Add the extra 2nd dimension
inputs = torch.cat(inputs).view(len(inputs), 1, -1)
hidden = (torch.randn(1, 1, 3), torch.randn(1, 1, 3))  # clean out hidden state
out, hidden = lstm(inputs, hidden)
print(out)
print(hidden)

nn.Embedding(vocab_size, embedding_dim)

tensor([[[-0.1250,  0.0168,  0.2212]],

        [[-0.0252,  0.1167,  0.1637]],

        [[ 0.1883,  0.2453,  0.1219]]], grad_fn=<StackBackward>)
(tensor([[[0.1883, 0.2453, 0.1219]]], grad_fn=<StackBackward>), tensor([[[0.2746, 0.3955, 0.1887]]], grad_fn=<StackBackward>))
